### ISSUE TITLE
os login error: user email not specified

### ISSUE THREAD

**Issue by vkuragin-clgx** [googleapis/java-os-login#180]
Sample application:
```
 public static void main(String[] args) throws Exception {
        try (OsLoginServiceClient osLoginServiceClient = OsLoginServiceClient.create()) {
            LoginProfile loginProfile = osLoginServiceClient.getLoginProfile("<account>");
            System.out.println(loginProfile.toString());
        }
}
```

Fails with error:

> 
> Exception in thread "main" com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: User email not specified.
> 	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
> 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
> 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
> 	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
> 	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
> 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1050)
> 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
> 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1176)
> 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
> 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:760)
> 	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:522)
> 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:497)
> 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
> 	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
> 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
> 		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
> 		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
> 		at com.google.cloud.oslogin.v1.OsLoginServiceClient.getLoginProfile(OsLoginServiceClient.java:409)
> 		at com.google.cloud.oslogin.v1.OsLoginServiceClient.getLoginProfile(OsLoginServiceClient.java:385)
> 		at org.edg.viper.taxroll.App.main(App.java:22)

I do not see any option to set this email in client settings?

**Comment by vkuragin-clgx** [comment]
The error was due to improperly specified account name, should be:
`"users/<serviceaccount>@<project>.iam.gserviceaccount.com"`
